-- Generated by HyprMod

-- Settings
hl.config({
    dwindle = {
        preserve_split = true,
    },
    general = {
        gaps_in = 1,
        gaps_out = 6,
    },
    input = {
        kb_options = "caps:escape",
    },
})
